// Dynamic import to avoid SSR issues
export async function downloadPDF(elementId: string, filename: string): Promise<void> {
  const html2pdf = (await import('html2pdf.js')).default;
  const originalElement = document.getElementById(elementId);
  if (!originalElement) throw new Error('Element not found for PDF export');

  // Create a wrapper for the PDF purely for print formatting
  const printWrapper = document.createElement('div');
  printWrapper.className = 'pdf-export-wrapper bg-white text-text-primary';
  
  // Create a professional header
  const header = document.createElement('div');
  header.style.marginBottom = '20px';
  header.innerHTML = `
    <h1 style="font-size: 32px; font-weight: 700; color: #111; margin: 0 0 8px 0; font-family: Inter, sans-serif;">
      ${filename}
    </h1>
    <div style="font-size: 13px; color: #666; margin-bottom: 24px; border-bottom: 2px solid #E8E8E8; padding-bottom: 16px; font-family: Inter, sans-serif;">
      Generated by New-S13n &nbsp;&bull;&nbsp; ${new Date().toLocaleDateString()}
    </div>
  `;
  
  // Clone the content so we don't modify the live DOM temporarily
  const clonedContent = originalElement.cloneNode(true) as HTMLElement;
  clonedContent.id = ''; // Remove ID to prevent duplicates
  
  printWrapper.appendChild(header);
  printWrapper.appendChild(clonedContent);
  
  // We don't need to append it to the DOM! html2pdf will handle detacted elements automatically.
  // Appending with negative coordinates causes html2canvas to draw the content out of bounds, resulting in a blank PDF.
  printWrapper.style.width = '800px'; // fixed A4-ish pixel width to prevent fluidity stretching
  printWrapper.style.padding = '20px'; // breathing room

  const opt = {
    margin: [15, 15, 20, 15], // Top, Right, Bottom, Left
    filename: `${filename}.pdf`,
    image: { type: 'jpeg', quality: 1.0 },
    html2canvas: { 
      scale: 2, // High resolution
      useCORS: true, 
      letterRendering: true,
      windowWidth: 800,
      scrollY: 0
    },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    pagebreak: { 
      mode: ['css', 'legacy'],
      avoid: ['pre', 'table', 'img', 'blockquote', 'li', 'h1', 'h2', 'h3'] 
    },
  };

  await html2pdf().set(opt).from(printWrapper).save();
}

